import Head from 'next/head'

export default function Home() {
  return (
      <div>
        <Head>
          <title>미니코드 홈</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
          <script async
                  src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9658548369352576"
                  crossOrigin="anonymous"></script>
        </Head>

        <main className={'main'}>
          <img src={'/img_main.png'} alt={'메인이미지'} width={'100%'}/>
        </main>
      </div>
  )
}
